Get involved
taangle/thinqtv-android pull request #3
Opened 2020-02-23 21:01 UTC by anibalb2500

Added the following:
- A button on the home page that goes to the Get Involved page.
- The Get involved page. 
- The "How to apply" Page

The Thinq.tv button on the top of both new pages acts as a home button.

2020-02-25 04:00 UTC, taangle requested changes
When renaming things like I requested, make sure you do it with the 'Refactor' option so that the name gets updated everywhere.

2020-02-25 04:00 UTC, taangle commented on .idea/misc.xml
> +  <component name="ProjectRootManager" version="2" languageLevel="JDK_1_8" project-jdk-name="1.8" project-jdk-type="JavaSDK">
We don't want to make changes like this to the master branch, I recommend getting rid of this.

2020-02-25 04:00 UTC, taangle commented on app/build.gradle
> +    implementation('org.jitsi.react:jitsi-meet-sdk:2.+') { transitive = true }
Similarly here, these changes should stay local.

2020-02-25 04:00 UTC, taangle commented on app/src/main/java/com/thinqtv/thinqtv_android/getInvolve.java
> +
Get rid of these unnecessary spaces.

2020-02-25 04:00 UTC, taangle commented on app/src/main/java/com/thinqtv/thinqtv_android/getInvolve.java
> +public class getInvolve extends AppCompatActivity {
Class names should be capitalized.

2020-02-25 04:00 UTC, taangle commented on app/src/main/java/com/thinqtv/thinqtv_android/getInvolved2.java
> +public class getInvolved2 extends AppCompatActivity {
Capitalize this class name, and also rename it to something more descriptive, like GetInvolvedApplyNowPage.

2020-02-25 22:44 UTC, anibalb2500 commented on app/src/main/java/com/thinqtv/thinqtv_android/getInvolved2.java
> +public class getInvolved2 extends AppCompatActivity {
Resolved.

2020-02-25 22:45 UTC, anibalb2500 commented on app/src/main/java/com/thinqtv/thinqtv_android/getInvolve.java
> +public class getInvolve extends AppCompatActivity {
Resolved.

2020-02-25 22:45 UTC, anibalb2500 commented on app/src/main/java/com/thinqtv/thinqtv_android/getInvolve.java
> +
Resolved.

2020-02-26 07:00 UTC, taangle approved these changes

2020-02-26 07:00 UTC, merged